version: '2'
services:
    azure-iotedge:
        image: wmucdev.azurecr.io/azure-iot-edge:1.1.1-1.0-alpha.1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - hub 
        environment: 
          DEVICE_CONNECTION_STR: ${DEVICE_CONNECTION_STR}
        restart: unless-stopped
        logging:
          driver: ${LOGGING_DRIVER}
          options:
            max-size: "10m"
            max-file: "1"
            compress: "false"

networks:
    hub:
        driver: bridge
