version: "2"

services:
  wm-node-red:
    image: weidmuellerucontrol.azurecr.io/wm-node-red:1.2.0-1.0-alpha.1 
    container_name: wm-node-red 
    network_mode: "host"
    volumes:
      - wm-node-red:/data
    environment: 
              - PORT=${PORT}
