version: "2"

services:
  wm-node-red:
    image: wmucdev.azurecr.io/wm-node-red:1.1.2-1.0-alpha.1 
    container_name: wm-node-red 
    network_mode: "host"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: "10m"
        max-file: "1"        
        compress: "false"
    volumes:
      - wm-node-red:/data
    environment: 
      PORT: ${PORT}
